name: Continuous Integration
on: [push, pull_request]
jobs:
  check:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Check Lint
        run: yarn format:check
